version: "3.7"

networks:
  mbevents-network:
    driver:
      bridge

services:
  db:
    networks:
      - mbevents-network
    image: postgres
    container_name: mbevents_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /tmp
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    environment: 
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?schema=public
    networks:
      - mbevents-network
    command: > 
        sh -c "npx prisma migrate dev &&
               npx prisma generate &&
               npm run dev"
    restart: always
    depends_on:
      - db
    ports:
      - '3333:3333'
    build: .
    volumes:
      - .:/src

    
    